services:
  yt-dlp-web:
    image: ghcr.io/tues8557-source/yt-dlp-web:latest
    pull_policy: always
    container_name: yt-dlp
    user: 1026:100 # User Id, Group Id Setting
    environment:
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   ex)
       AUTH_SECRET: "use random API Key generator"
       CREDENTIAL_USERNAME: "your id"
       CREDENTIAL_PASSWORD: "your password"
       API_TOKEN: "use random API Key generator"
    volumes:
      - /volume1/docker/yt/downloads:/downloads # Downloads folder, this is example
      - /volume1/docker/yt/cache:/cache         # Cache folder, this is example
    ports:
      - 3000:3000 # Web Page Port Mapping
    restart: unless-stopped